"""Renders the top-level landing page that picks a team.

The page is a static HTML index at the site root that links to each
registered team's `/<slug>/index.html`. Up/Down arrows move a focus
highlight through the teams (Enter follows the focused link). The page
is regenerated by analyze_git.py at the end of each run so adding a
team is a config-only change in teams.py.

Visual style is the same paper-and-ink editorial system the per-team
dashboards use (Fraunces / Instrument Sans / JetBrains Mono on cream
with Mozilla red accents) so the landing page and the dashboards read
as one product, not two.
"""

from reviewstats.teams import Team


_FAVICON = (
    "data:image/svg+xml;utf8,"
    "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'>"
    "<rect width='64' height='64' rx='12' fill='%23FF0039'/>"
    "<text x='32' y='49' "
    "font-family='-apple-system, BlinkMacSystemFont, Segoe UI, "
    "Helvetica, Arial, sans-serif' "
    "font-weight='900' font-size='52' fill='white' "
    "text-anchor='middle'>m</text></svg>"
)


_FONTS = (
    '<link rel="preconnect" href="https://fonts.googleapis.com">'
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
    '<link href="https://fonts.googleapis.com/css2?'
    'family=Fraunces:ital,opsz,wght,SOFT@0,9..144,300..900,0..100;'
    '1,9..144,300..900,0..100'
    '&family=Instrument+Sans:ital,wght@0,400..700;1,400..700'
    '&family=JetBrains+Mono:wght@400..700&display=swap" rel="stylesheet">'
)


_STYLE = """
:root {
  --paper: #FAF7F0;
  --paper-warm: #F2EBDC;
  --ink: #16110D;
  --ink-soft: #3B342D;
  --muted: #8B8378;
  --rule: #E6DECD;
  --rule-soft: #F0E9D9;
  --surface: #FFFFFF;
  --red: #FF0039;
  --red-deep: #B3002A;

  --serif: 'Fraunces', 'Iowan Old Style', Georgia, serif;
  --sans: 'Instrument Sans', -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
  --mono: 'JetBrains Mono', ui-monospace, SFMono-Regular, monospace;
}
* { box-sizing: border-box; }
body {
  font-family: var(--sans);
  margin: 0;
  background: var(--paper);
  color: var(--ink);
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

.masthead {
  max-width: 980px;
  margin: 0 auto;
  width: 100%;
  padding: 48px 40px 18px;
  position: relative;
}
.eyebrow {
  font-family: var(--mono);
  font-size: 10.5px;
  text-transform: uppercase;
  letter-spacing: 0.22em;
  color: var(--muted);
  margin: 0 0 16px;
  display: flex;
  align-items: center;
  gap: 14px;
}
.eyebrow::before, .eyebrow::after {
  content: '';
  flex: 0 0 auto;
  height: 1px;
  background: var(--rule);
}
.eyebrow::before { width: 32px; }
.eyebrow::after  { flex: 1; }

h1.title {
  font-family: var(--serif);
  font-variation-settings: "opsz" 120, "wght" 500, "SOFT" 30;
  font-size: clamp(42px, 6.4vw, 72px);
  line-height: 0.96;
  letter-spacing: -0.03em;
  font-weight: 500;
  margin: 0 0 14px;
  color: var(--ink);
}
h1.title em {
  font-style: italic;
  font-variation-settings: "opsz" 120, "wght" 500, "SOFT" 100;
  color: var(--red);
  letter-spacing: -0.022em;
}

.lede {
  font-family: var(--serif);
  font-variation-settings: "opsz" 18, "wght" 400, "SOFT" 60;
  font-size: 16px;
  line-height: 1.45;
  color: var(--ink-soft);
  max-width: 620px;
  margin: 0 0 18px;
  font-weight: 400;
}
.lede em {
  font-style: italic;
  color: var(--ink);
}

.meta-row {
  font-family: var(--mono);
  font-size: 10.5px;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--muted);
  display: flex;
  align-items: baseline;
  gap: 12px;
  flex-wrap: wrap;
}
.meta-row .sep { color: var(--rule); }

main {
  flex: 1;
  max-width: 980px;
  margin: 0 auto;
  padding: 8px 40px 36px;
  width: 100%;
}

.toc-rule {
  height: 1px;
  background: var(--ink);
  margin: 0;
}
.toc-rule.thin { background: var(--rule); }

.toc-header {
  display: grid;
  grid-template-columns: 48px 1fr 130px 24px;
  gap: 20px;
  padding: 8px 0;
  align-items: baseline;
  font-family: var(--mono);
  font-size: 9.5px;
  letter-spacing: 0.14em;
  text-transform: uppercase;
  color: var(--muted);
}
.toc-header span { font-weight: 500; }
.toc-header .toc-h-count { text-align: right; }

.team-row {
  display: grid;
  grid-template-columns: 48px 1fr 130px 24px;
  gap: 20px;
  padding: 16px 0 18px;
  align-items: baseline;
  text-decoration: none;
  color: var(--ink);
  border-top: 1px solid var(--rule);
  transition: background 0.18s, padding-left 0.2s ease;
  position: relative;
}
.team-row:first-of-type { border-top: none; }
.team-row::after {
  content: '';
  position: absolute;
  left: 0; top: -1px;
  height: 1px; width: 0;
  background: var(--red);
  transition: width 0.28s ease;
}
/* Exactly one row is highlighted at a time — the "selection". Both
   hovering and the Up/Down keys set it via JS (`.is-selected`), so
   there's only ever one highlight and the keyboard stays in control
   even while the cursor rests over the list. Using a JS-driven class
   instead of CSS :hover/:focus is what avoids two rows lighting up. */
.team-row.is-selected {
  background: var(--paper-warm);
  padding-left: 14px;
}
/* Drop the default ring — the selection highlight (warm bg + full-width
   red top rule + red name/arrow) is the visible focus indicator. */
.team-row:focus { outline: none; }
.team-row.is-selected::after { width: 100%; }
.team-row.is-selected .row-arrow { transform: translateX(6px); color: var(--red); }
.team-row.is-selected .row-name { color: var(--red); }

.row-num {
  font-family: var(--serif);
  font-variation-settings: "opsz" 30, "wght" 400, "SOFT" 50;
  font-style: italic;
  font-size: 24px;
  line-height: 1;
  color: var(--muted);
  letter-spacing: -0.01em;
}
.row-meta { min-width: 0; }
.row-name {
  font-family: var(--serif);
  font-variation-settings: "opsz" 30, "wght" 500, "SOFT" 30;
  font-size: 22px;
  line-height: 1.1;
  letter-spacing: -0.012em;
  font-weight: 500;
  color: var(--ink);
  margin: 0 0 5px;
  transition: color 0.18s;
}
.row-paths {
  font-family: var(--mono);
  font-size: 11.5px;
  color: var(--ink-soft);
  line-height: 1.5;
  margin: 0;
  word-break: break-word;
}
.row-paths .sep {
  color: var(--rule);
  margin: 0 4px;
}
.row-stats {
  font-family: var(--mono);
  font-size: 10.5px;
  color: var(--muted);
  text-transform: uppercase;
  letter-spacing: 0.06em;
  text-align: right;
  line-height: 1.4;
}
.row-stats strong {
  display: block;
  font-family: var(--serif);
  font-variation-settings: "opsz" 30, "wght" 500;
  font-style: italic;
  font-size: 19px;
  color: var(--ink);
  letter-spacing: -0.01em;
  font-weight: 500;
  margin-bottom: 1px;
  text-transform: none;
}
.row-arrow {
  font-family: var(--serif);
  font-variation-settings: "opsz" 30, "wght" 400;
  font-size: 22px;
  color: var(--muted);
  line-height: 1;
  transition: transform 0.22s ease, color 0.18s;
  text-align: right;
}

footer {
  font-family: var(--mono);
  font-size: 9.5px;
  color: var(--muted);
  text-transform: uppercase;
  letter-spacing: 0.12em;
  text-align: center;
  padding: 16px 40px 22px;
  border-top: 1px solid var(--rule);
  max-width: 980px;
  margin: 16px auto 0;
  width: 100%;
}
footer a {
  color: var(--ink);
  text-decoration: none;
  border-bottom: 1px solid var(--rule);
  transition: border-color 0.15s, color 0.15s;
}
footer a:hover {
  color: var(--red);
  border-bottom-color: var(--red);
}

@media (max-width: 720px) {
  .masthead { padding: 32px 24px 18px; }
  main { padding: 8px 24px 36px; }
  .team-row, .toc-header {
    grid-template-columns: 40px 1fr;
    gap: 14px;
  }
  .team-row .row-stats, .team-row .row-arrow,
  .toc-header .toc-h-count, .toc-header .toc-h-arrow {
    grid-column: 1 / -1;
    text-align: left;
  }
  .row-name { font-size: 20px; }
  .row-num  { font-size: 22px; }
}
""".strip()


def _path_cells(paths: tuple[str, ...]) -> str:
    """Join multi-root paths with a dot separator that pairs nicely
    with the mono row-paths styling — visual rhythm matters when a
    team owns four or five trees and the cell line-wraps."""
    return '<span class="sep">·</span>'.join(paths)


def _team_row(team: Team, index: int) -> str:
    n = len(team.members)
    roster = f"{n} listed reviewer" + ("s" if n != 1 else "")
    # `display_name` runs flush against the closing div (no leading or
    # trailing whitespace) so callers can pin the literal
    # `>{display_name}<` in tests.
    return (
        f'<a class="team-row" href="{team.slug}/index.html">'
        f'<div class="row-num">{index:02d}</div>'
        f'<div class="row-meta">'
        f'<div class="row-name">{team.display_name}</div>'
        f'<div class="row-paths">{_path_cells(team.paths)}</div>'
        f'</div>'
        f'<div class="row-stats"><strong>{n}</strong>{roster}</div>'
        f'<div class="row-arrow">→</div>'
        f'</a>'
    )


def render_landing_page(teams: list[Team]) -> str:
    """Return a fully self-contained HTML document listing every team
    as a clickable row. Up/Down arrows move a focus highlight through
    the rows; Enter follows the focused link."""
    rows = [
        _team_row(team, i + 1)
        for i, team in enumerate(teams)
    ]
    rows_html = "\n  ".join(rows)
    n_teams = len(teams)
    dashboards_word = "dashboard" + ("s" if n_teams != 1 else "")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Mozilla Team Dashboards — pick a team</title>
<link rel="icon" type="image/svg+xml" href="{_FAVICON}">
{_FONTS}
<style>{_STYLE}</style>
</head>
<body>

<div class="masthead">
  <p class="eyebrow"><span>Mozilla · Research</span></p>
  <h1 class="title">Team<br><em>Dashboards</em></h1>
  <p class="lede">A six-month read on each review team — <em>who reviews what</em>, for whom, and how often (concentration, bottleneck risk, review-wait latency) — plus a digest of <em>what each component shipped</em> recently.</p>
  <div class="meta-row">
    <span>{n_teams} {dashboards_word}</span>
    <span class="sep">·</span>
    <span>Refreshed weekly</span>
    <span class="sep">·</span>
    <span>Rolling 6-month window</span>
  </div>
</div>

<main>
  <div class="toc-rule"></div>
  <div class="toc-header">
    <span></span>
    <span>Team · Owned paths</span>
    <span class="toc-h-count">Roster</span>
    <span class="toc-h-arrow"></span>
  </div>
  <div class="toc-rule thin"></div>

  {rows_html}

  <div class="toc-rule"></div>
</main>

<footer>
  Source · <a href="https://github.com/alastor0325/firefox-review-stats">alastor0325/firefox-review-stats</a>
</footer>

<script>
// Up / Down move the selection highlight through the team rows so the
// picker is keyboard-drivable like the per-team dashboards. Mouse and
// keyboard share ONE selection (last interaction wins): hovering a row
// selects it, and the arrows step from wherever the selection is — so
// only one row is ever highlighted and the keyboard keeps working even
// while the cursor rests over the list. Enter follows the selected
// row's link natively (each row is a focused <a>).
(function teamKeyboardNav() {{
  const rows = Array.from(document.querySelectorAll('a.team-row'));
  if (!rows.length) return;
  let sel = -1;  // index of the highlighted row; -1 = nothing yet
  function select(i) {{
    rows.forEach((r, j) => r.classList.toggle('is-selected', j === i));
    sel = i;
    rows[i].focus({{ preventScroll: true }});
  }}
  // Hovering a row makes it the selection (mouseenter, not CSS :hover,
  // so it can't fight the keyboard highlight).
  rows.forEach((r, i) => r.addEventListener('mouseenter', () => select(i)));
  document.addEventListener('keydown', (e) => {{
    if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp') return;
    // Leave OS/browser-reserved arrow combos alone.
    if (e.metaKey || e.altKey || e.ctrlKey || e.shiftKey) return;
    const dir = e.key === 'ArrowDown' ? 1 : -1;
    // Nothing selected yet: Down → first row, Up → last row.
    const next = sel === -1
      ? (dir === 1 ? 0 : rows.length - 1)
      : (sel + dir + rows.length) % rows.length;
    select(next);
    e.preventDefault();
  }});
}})();
</script>

</body>
</html>
"""
