"""Renders the top-level landing page that picks a team.

The page is a static HTML index at the site root that links to each
registered team's `/<slug>/index.html`. Playback is highlighted as
the default. The page is regenerated by analyze_git.py at the end
of each run so adding a team is a config-only change in teams.py.
"""

from reviewstats.teams import PLAYBACK_TEAM, Team


_FAVICON = (
    "data:image/svg+xml;utf8,"
    "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'>"
    "<rect width='64' height='64' rx='12' fill='%23FF0039'/>"
    "<text x='32' y='49' "
    "font-family='-apple-system, BlinkMacSystemFont, Segoe UI, "
    "Helvetica, Arial, sans-serif' "
    "font-weight='900' font-size='52' fill='white' "
    "text-anchor='middle'>m</text></svg>"
)


_STYLE = """
:root {
  --bg: #f6f7f9;
  --fg: #1c1f24;
  --muted: #6b7280;
  --card: #ffffff;
  --accent: #3b82f6;
  --moz-red: #FF0039;
}
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI",
               Helvetica, Arial, sans-serif;
  margin: 0;
  background: var(--bg);
  color: var(--fg);
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}
header {
  background: var(--fg);
  color: var(--bg);
  padding: 32px 32px 24px;
}
header h1 { margin: 0; font-size: 22px; font-weight: 600; }
header .subtitle { margin-top: 6px; font-size: 13px; opacity: 0.7; }
main {
  flex: 1;
  max-width: 960px;
  margin: 0 auto;
  padding: 32px 24px 48px;
  width: 100%;
}
.intro {
  font-size: 14px;
  color: var(--muted);
  margin: 0 0 24px;
}
.team-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 16px;
}
.team-card {
  display: block;
  text-decoration: none;
  color: inherit;
  background: var(--card);
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  padding: 20px 22px;
  transition: border-color 0.15s, box-shadow 0.15s, transform 0.15s;
}
.team-card:hover {
  border-color: var(--accent);
  box-shadow: 0 4px 12px rgba(59, 130, 246, 0.15);
  transform: translateY(-1px);
}
.team-card .name {
  font-size: 16px;
  font-weight: 600;
  margin: 0 0 6px;
  display: flex;
  align-items: center;
  gap: 8px;
}
.default-badge {
  font-size: 10px;
  background: var(--accent);
  color: white;
  padding: 2px 6px;
  border-radius: 4px;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  font-weight: 700;
}
.team-card .paths {
  font-size: 12px;
  color: var(--muted);
  font-family: ui-monospace, SFMono-Regular, monospace;
  margin: 0;
}
.team-card .roster {
  font-size: 11px;
  color: var(--muted);
  margin: 8px 0 0;
}
footer {
  font-size: 11px;
  color: var(--muted);
  text-align: center;
  padding: 16px;
  border-top: 1px solid #e5e7eb;
}
""".strip()


def render_landing_page(teams: list[Team]) -> str:
    """Return a fully self-contained HTML document listing every team
    as a clickable card. Playback gets a 'default' badge so a first-
    time visitor knows where to start."""
    cards = []
    for team in teams:
        is_default = team.slug == PLAYBACK_TEAM.slug
        badge = (
            '<span class="default-badge">Default</span>' if is_default else ""
        )
        paths_str = ", ".join(team.paths)
        roster_str = (
            f"{len(team.members)} listed reviewer"
            + ("s" if len(team.members) != 1 else "")
        )
        cards.append(
            f'<a class="team-card" href="{team.slug}/index.html">'
            f'<p class="name">{team.display_name}{badge}</p>'
            f'<p class="paths">{paths_str}</p>'
            f'<p class="roster">{roster_str}</p>'
            f'</a>'
        )
    cards_html = "\n      ".join(cards)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Mozilla Reviewer Load — pick a team</title>
<link rel="icon" type="image/svg+xml" href="{_FAVICON}">
<style>{_STYLE}</style>
</head>
<body>
<header>
  <h1>Mozilla Reviewer Load</h1>
  <div class="subtitle">Per-team reviewer activity dashboards. Pick a team to drill in.</div>
</header>
<main>
  <p class="intro">Each dashboard covers the past 6 months of patches landed under the team's owned paths. Data refreshes weekly.</p>
  <div class="team-grid">
      {cards_html}
  </div>
</main>
<footer>Source: <a href="https://github.com/alastor0325/firefox-review-stats">alastor0325/firefox-review-stats</a></footer>
</body>
</html>
"""
